
trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
pool:
  vmImage: 'windows-latest'
steps:
- script: npm install
  displayName: 'Run install packages'
- script: |
    npm run ci
  displayName: 'Run lint/build/test'
  